docker_compose('./docker/docker-compose.yml')
dc_resource('api', labels='api')
local_resource('Composer Install', cmd='docker run -i -v $PWD/root-app:/root-app spiral-ddd-bolierplate_api:latest su spiral -c "composer install"', labels=['jobs'])
local_resource('Composer quality', cmd='docker run -i -v $PWD/root-app:/root-app spiral-ddd-bolierplate_api:latest su spiral -c "composer quality"', labels=['jobs'])
local_resource('Run Tests', cmd='docker run -i -v $PWD/root-app:/root-app spiral-ddd-bolierplate_api:latest su spiral -c "composer test"', labels=['jobs'])
local_resource('Rector', cmd='docker run -i -v $PWD/root-app:/root-app spiral-ddd-bolierplate_api:latest su spiral -c "./vendor/bin/rector"', labels=['jobs'])
local_resource('Psalm', cmd='docker run -i -v $PWD/root-app:/root-app spiral-ddd-bolierplate_api:latest su spiral -c "composer psalm"', labels=['jobs'])
local_resource('PhpCs', cmd='docker run -i -v $PWD/root-app:/root-app spiral-ddd-bolierplate_api:latest su spiral -c "composer phpcs"', labels=['jobs'])
local_resource('PhpBf', cmd='docker run -i -v $PWD/root-app:/root-app spiral-ddd-bolierplate_api:latest su spiral -c "composer phpcbf"', labels=['jobs'])
local_resource('Deptrac', cmd='docker run -i -v $PWD/root-app:/root-app spiral-ddd-bolierplate_api:latest su spiral -c "composer deptrac"', labels=['jobs'])
